BIST_STOCKS = [
    "AEFES.IS",
    "AKBNK.IS",
    "AKSA.IS",
    "AKSEN.IS",
    "ALARK.IS",
    "ALTNY.IS",
    "ANSGR.IS",
    "ARCLK.IS",
    "ASELS.IS",
    "ASTOR.IS",
    "BALSU.IS",
    "BERA.IS",
    "BIMAS.IS",
    "BRSAN.IS",
    "BRYAT.IS",
    "BSOKE.IS",
    "BTCIM.IS",
    "CANTE.IS",
    "CCOLA.IS",
    "CIMSA.IS",
    "CVKMD.IS",
    "CWENE.IS",
    "DAPGM.IS",
    "DOAS.IS",
    "DOHOL.IS",
    "DSTKF.IS",
    "ECILC.IS",
    "EFOR.IS",
    "EKGYO.IS",
    "ENERY.IS",
    "ENJSA.IS",
    "ENKAI.IS",
    "EREGL.IS",
    "ESEN.IS",
    "EUPWR.IS",
    "EUREN.IS",
    "FENER.IS",
    "FROTO.IS",
    "GARAN.IS",
    "GENIL.IS",
    "GESAN.IS",
    "GLRMK.IS",
    "GRSEL.IS",
    "GRTHO.IS",
    "GSRAY.IS",
    "GUBRF.IS",
    "HALKB.IS",
    "HEKTS.IS",
    "IEYHO.IS",
    "ISCTR.IS",
    "ISMEN.IS",
    "IZENR.IS",
    "KCHOL.IS",
    "KLRHO.IS",
    "KRDMD.IS",
    "KTLEV.IS",
    "KUYAS.IS",
    "MAGEN.IS",
    "MAVI.IS",
    "MGROS.IS",
    "MIATK.IS",
    "MPARK.IS",
    "OBAMS.IS",
    "ODAS.IS",
    "ODINE.IS",
    "OTKAR.IS",
    "OYAKC.IS",
    "PAHOL.IS",
    "PASEU.IS",
    "PATEK.IS",
    "PETKM.IS",
    "PGSUS.IS",
    "PSGYO.IS",
    "QUAGR.IS",
    "RALYH.IS",
    "REEDR.IS",
    "SAHOL.IS",
    "SARKY.IS",
    "SASA.IS",
    "SISE.IS",
    "SKBNK.IS",
    "SOKM.IS",
    "TAVHL.IS",
    "TCELL.IS",
    "THYAO.IS",
    "TKFEN.IS",
    "TOASO.IS",
    "TRALT.IS",
    "TRENJ.IS",
    "TRMET.IS",
    "TSKB.IS",
    "TTKOM.IS",
    "TUKAS.IS",
    "TUPRS.IS",
    "TURSG.IS",
    "ULKER.IS",
    "VAKBN.IS",
    "VESTL.IS",
    "YKBNK.IS",
    "ZOREN.IS",
]

BACKTEST_YEARS = 2

PIVOT_METHODS = ["classic", "fibonacci", "camarilla", "demark", "woodie"]

TIMEFRAMES = ["daily", "weekly", "monthly"]

# "Touch": fiyatın pivot seviyesine ne kadar yaklaştığıdır.
TOUCH_THRESHOLD_PCT = 0.001

# "Break": fiyatın pivot seviyesini ne kadar geçtiğidir.
BREAK_THRESHOLD_PCT = 0.002

# Confluence zone: farklı yöntemlerden gelen pivot seviyelerinin, birbirine bu yüzde kadar yakın olması durumunda "confluence" sayılmasıdır.
CONFLUENCE_TOLERANCE_PCT = 0.003

LOW_SAMPLE_SIZE_THRESHOLD = 30

DATABASE_PATH = "data/bist_pivot.db"